### ISSUE TITLE
Custom styling of Select itself

### ISSUE THREAD

**Issue by alltonp** [MadonnaMat/elm-select-two#3]
Hi,

Firstly, thank you for this widget, it was very easy to integrate into my app and works nicely.

I noticed that it's possible to provide customHtml, is there some mechanism to do the same for the select element itself?

For example, I'm using multi-select but don't want the black border, whereas the single select has a grey border but has reduced height. I would really like to be able to control these (and other) styles. See [example page](https://madonnamat.github.io/elm-select-two/example/). Is this possible?

Many thanks,
Paulos

**Comment by MadonnaMat** [comment]
You should be able to change any style with css as you would regular Select2 dropdowns, for instance, if you want to change the color of the borders add a stylesheet or style tag with:
```
.select2-container--default.select2-container--focus .select2-selection--multiple {
    border: 1px solid <whatever>;
}
```
to it.
