### ISSUE TITLE
Hide dropdown when the control loses focus

### ISSUE THREAD

**Issue by pawanpoudel** [MadonnaMat/elm-select-two#4]
Hi there,

Thank you so much for creating this package. I looked through the documentation and your example code to see if there is a way to hide the drop-down (shown below) when the control loses focus, but I couldn't find one.

![select-two-hide-dropdown](https://user-images.githubusercontent.com/115379/40318775-bc0c4bde-5cf3-11e8-9cca-40e95ec47eb9.png)

I'd also like to hide the "No Results Found" message (shown below) when I haven't entered anything yet. Is there a way to achieve that? Right now that message is displayed as soon as the control gains focus. 

![select-two-no-results-found](https://user-images.githubusercontent.com/115379/40318557-fa8f6392-5cf2-11e8-914e-012b4e7ca42d.png)

**Comment by MadonnaMat** [comment]
Right now, the only way for the dropdown to be closed is from a click away and the `select2Close` action. I believe you can hid the No Results Found text by just setting it to an empty string, but I haven't tried that yet.
